package info.toegepaste.www.entity;
// Generated 13-okt-2014 10:31:43 by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;




/**
 * Score generated by hbm2java
 */
@Entity
public class Score  implements java.io.Serializable {

    @Id
    @GeneratedValue
     private Integer id;
    @ManyToOne
    @JoinColumn(name="studentId")
     private Student student;
    @ManyToOne
    @JoinColumn(name="testId")
     private Test test;
     private double punt;

    public Score() {
    }

    public Score(Student student, Test test, double punt) {
       this.student = student;
       this.test = test;
       this.punt = punt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Test getTest() {
        return this.test;
    }
    
    public void setTest(Test test) {
        this.test = test;
    }
    public double getPunt() {
        return this.punt;
    }
    
    public void setPunt(double punt) {
        this.punt = punt;
    }




}


