package info.toegepaste.www.entity;
// Generated 13-okt-2014 10:31:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;

/**
 * Student generated by hbm2java
 */
@Entity
@NamedQueries({
    @NamedQuery(name = "Student.findByNr", query = "SELECT s FROM Student s WHERE s.studentnummer = :nr"),
    @NamedQuery(name = "Student.findById", query = "SELECT s FROM Student s WHERE s.id = :id")
})
public class Student  implements java.io.Serializable {

    @Id
    @GeneratedValue
     private Integer id;
    @ManyToOne
    @JoinColumn(name="klasId")
     private Klas klas;
     private String studentnummer;
     private String naam;
     private String emailadres;
     @OneToMany
     private List<Score> scores = new ArrayList<Score>(0);

    public Student() {
    }

	
    public Student(Klas klas, String studentnummer, String naam) {
        this.klas = klas;
        this.studentnummer = studentnummer;
        this.naam = naam;
    }
    public Student(Klas klas, String studentnummer, String naam, String emailadres, List<Score> scores) {
       this.klas = klas;
       this.studentnummer = studentnummer;
       this.naam = naam;
       this.emailadres = emailadres;
       this.scores = scores;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Klas getKlas() {
        return this.klas;
    }
    
    public void setKlas(Klas klas) {
        this.klas = klas;
    }
    public String getStudentnummer() {
        return this.studentnummer;
    }
    
    public void setStudentnummer(String studentnummer) {
        this.studentnummer = studentnummer;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getEmailadres() {
        return this.emailadres;
    }
    
    public void setEmailadres(String emailadres) {
        this.emailadres = emailadres;
    }
    public List<Score> getScores() {
        return this.scores;
    }
    
    public void setScores(List<Score> scores) {
        this.scores = scores;
    }




}


