package info.toegepaste.www.entity;
// Generated 13-okt-2014 10:31:43 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

/**
 * Test generated by hbm2java
 */
@Entity
public class Test  implements java.io.Serializable {

    @Id
    @GeneratedValue
     private Integer id;
    @ManyToOne
    @JoinColumn(name="klasId")
     private Klas klas;
    @ManyToOne
    @JoinColumn(name="vakId")
     private Vak vak;
     private String naam;
     private double maxScore;
     @OneToMany
     private List<Score> scores = new ArrayList<Score>(0);

    public Test() {
    }

	
    public Test(Klas klas, Vak vak, String naam, double maxScore) {
        this.klas = klas;
        this.vak = vak;
        this.naam = naam;
        this.maxScore = maxScore;
    }
    public Test(Klas klas, Vak vak, String naam, double maxScore, List<Score> scores) {
       this.klas = klas;
       this.vak = vak;
       this.naam = naam;
       this.maxScore = maxScore;
       this.scores = scores;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Klas getKlas() {
        return this.klas;
    }
    
    public void setKlas(Klas klas) {
        this.klas = klas;
    }
    public Vak getVak() {
        return this.vak;
    }
    
    public void setVak(Vak vak) {
        this.vak = vak;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public double getMaxScore() {
        return this.maxScore;
    }
    
    public void setMaxScore(double maxScore) {
        this.maxScore = maxScore;
    }
    public List<Score> getScores() {
        return this.scores;
    }
    
    public void setScores(List<Score> scores) {
        this.scores = scores;
    }




}


